ALTER TABLE metas
    ADD COLUMN IF NOT EXISTS concluida BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS concluida_em TIMESTAMPTZ(6),
    ADD COLUMN IF NOT EXISTS notificacao_enviada BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS notificacao_enviada_em TIMESTAMPTZ(6);
